application: mixo-maxos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts
  
- url: /.*
  script: mixomaxos.app
  
libraries:
- name: jinja2
  version: "2.6"
